[versions]
agp = "8.13.0"
kotlin = "2.0.20"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
tensorflowLite = "2.17.0"
tensorflowLiteMetadata = "0.5.0"
tensorflowLiteSupport = "0.5.0"
faceDetection = "16.1.7"
ejmlSimple = "0.44.0"
coreKtx = "1.17.0"
appcompat = "1.6.1"
material = "1.10.0"
opencv = "4.10.0"
truth = "1.4.5"

[libraries]
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test" }
tensorflow-lite = { module = "org.tensorflow:tensorflow-lite", version.ref = "tensorflowLite" }
tensorflow-lite-metadata = { module = "org.tensorflow:tensorflow-lite-metadata", version.ref = "tensorflowLiteMetadata" }
tensorflow-lite-support = { module = "org.tensorflow:tensorflow-lite-support", version.ref = "tensorflowLiteSupport" }
face-detection = { module = "com.google.mlkit:face-detection", version.ref = "faceDetection" }
ejml-simple = { module = "org.ejml:ejml-simple", version.ref = "ejmlSimple" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
opencv = { module = "org.opencv:opencv", version.ref = "opencv" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

